image: node:10

cache:
  paths:
    - node_modules/

stages:
  - test
  - release

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run test:unit

publish:
  stage: release
  script:
    - npx semantic-release
