image: node:10

cache:
  paths:
  - node_modules/
  - .yarn

before_script:
  - apt-get update -qq && apt-get install
  - yarn install

stages:
  - test

jest_tests:
  stage: test
  script:
    - yarn test:unit
