image: node:10

cache:
  paths:
  - node_modules/
  - .yarn

stages:
  - test

jest_tests:
  stage: test
  before_script:
  - yarn config set cache-folder .yarn
  - yarn install
  script:
    - yarn test:unit
